# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [ ]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Exercício 1

In [7]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

n = np.array(np.random.rand(1000000))
l = list(np.random.rand(1000000))

In [16]:
%%time
n*2

CPU times: total: 0 ns
Wall time: 3.05 ms


array([0.8534907 , 1.91946695, 0.65203626, ..., 0.41629581, 1.97733307,
       0.54220376])

In [17]:
%%time
l*2

CPU times: total: 15.6 ms
Wall time: 14 ms


[0.14655929181808347,
 0.4060759889654214,
 0.11053090433123347,
 0.7940450212386976,
 0.4271431668824661,
 0.7406687148776528,
 0.25991310023250114,
 0.2553337984967501,
 0.7333860945740438,
 0.05028433377029928,
 0.3098386951086287,
 0.7466322395795728,
 0.047692436955572126,
 0.22907758530372657,
 0.012057750408577927,
 0.7425900341150757,
 0.6436997003112351,
 0.004673192148475169,
 0.06204533189750405,
 0.8344650268558154,
 0.3291090813201635,
 0.3920394308185471,
 0.8308237256219839,
 0.554322052503875,
 0.022615663876985437,
 0.9006853153765315,
 0.771768655474725,
 0.680938315939502,
 0.8782403349930814,
 0.40090735659350407,
 0.8120057246650735,
 0.07417170215034319,
 0.6199062054113732,
 0.8544203794723408,
 0.46727377813117843,
 0.9326550581424862,
 0.5829236817537479,
 0.5011875366597872,
 0.32083892721714236,
 0.6991074265719923,
 0.6717370502732546,
 0.20251586204029015,
 0.16797455741729783,
 0.9176930750291661,
 0.2068694508622826,
 0.27573404267407187,
 0.6880969216379

### Exercício 2

In [ ]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [18]:
ar = np.array(list(range(10)))
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
ar[5:8] = 0
ar

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

### Exercício 3

In [22]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
m = [[1,2,3], [4,5,6], [7,8,9]]
m[0]

[1, 2, 3]

### Exercício 4

In [41]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
m = [[1,3,2],[9,7,8],[5,4,3]]
[i[1:3] for i in m[0:2]]



[[3, 2], [7, 8]]

[[3, 2], [7, 8]]

### Exercício 5

In [43]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [45]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. 
# Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [54]:
[xarr[i] if cond[i] else yarr[i] for i in range(len(cond))]

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [5]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
A = list(np.random.rand(10))
A

[0.4329460266410482,
 0.1251740631276328,
 0.7242853037646187,
 0.35103745005152254,
 0.9218477160894109,
 0.4032761319531515,
 0.5287386240400791,
 0.3512137961453561,
 0.5528959499378362,
 0.16253372866359772]

In [14]:
with open('A.txt','w') as data:
    for i,v in enumerate(A):
        if i != (len(A)-1):
            data.write(str(v)+',')
        else:
            data.write(str(v))

In [12]:
len(A)

10

In [9]:
list(enumerate(A))

[(0, 0.4329460266410482),
 (1, 0.1251740631276328),
 (2, 0.7242853037646187),
 (3, 0.35103745005152254),
 (4, 0.9218477160894109),
 (5, 0.4032761319531515),
 (6, 0.5287386240400791),
 (7, 0.3512137961453561),
 (8, 0.5528959499378362),
 (9, 0.16253372866359772)]

In [26]:
with open('A.txt','r') as Adata: 
    B = Adata.read().split(',')
B

['0.4329460266410482',
 '0.1251740631276328',
 '0.7242853037646187',
 '0.35103745005152254',
 '0.9218477160894109',
 '0.4032761319531515',
 '0.5287386240400791',
 '0.3512137961453561',
 '0.5528959499378362',
 '0.16253372866359772']

### Exercício 8

In [55]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [58]:
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [80]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
import io
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
json = resp.json()
content = json[0]
pd.DataFrame(data=json, columns=list(content.keys())[6:],).head()

id              node_id  number  \
0  1150754239   I_kwDOAA0YD85Elx2_   46152   
1  1150730566  PR_kwDOAA0YD84zeutS   46151   
2  1150718001  PR_kwDOAA0YD84zesDq   46150   
3  1150712051   I_kwDOAA0YD85Elnjz   46149   
4  1150657784   I_kwDOAA0YD85ElaT4   46148   

                                               title  \
0     BUG: Styler cannot accept semicolon in CSS val   
1                             CLN/TYP: remove unused   
2          CI/TST: Fix xfail(strict=False) condition   
3  PERF: Series.fillna (that is part of DataFrame...   
4             BUG: to_hdf hangs without error messag   

                                                user  \
0  {'login': 'tehunter', 'id': 7980666, 'node_id'...   
1  {'login': 'jbrockmendel', 'id': 8078968, 'node...   
2  {'login': 'mroeschke', 'id': 10647082, 'node_i...   
3  {'login': 'jukiewiczm', 'id': 8179126, 'node_i...   
4  {'login': 'fab6', 'id': 3047695, 'node_id': 'M...   

                                              labels state  locked assignee  \
0  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open   False     None   
1                                                 []  open   False     None   
2  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open   False     None   
3  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open   False     None   
4  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open   False     None   

  assignees  ... comments            created_at            updated_at  \
0        []  ...        2  2022-02-25T18:56:12Z  2022-02-25T19:10:17Z   
1        []  ...        0  2022-02-25T18:22:38Z  2022-02-25T18:22:38Z   
2        []  ...        0  2022-02-25T18:06:00Z  2022-02-25T18:06:18Z   
3        []  ...        0  2022-02-25T17:58:09Z  2022-02-25T17:58:09Z   
4        []  ...        7  2022-02-25T16:51:06Z  2022-02-25T18:27:41Z   

  closed_at author_association active_lock_reason  \
0      None        CONTRIBUTOR               None   
1      None             MEMBER               None   
2      None             MEMBER               None   
3      None               NONE               None   
4      None               NONE               None   

                                                body  \
0  ### Pandas version checks\n\n- [X] I have chec...   
1  - [ ] closes #xxxx (Replace xxxx with the Gith...   
2  - xref #46144\r\n- [x] [Tests added and passed...   
3  ### Pandas version checks\n\n- [X] I have chec...   
4  ### Pandas version checks\n\n- [X] I have chec...   

                                           reactions  \
0  {'url': 'https://api.github.com/repos/pandas-d...   
1  {'url': 'https://api.github.com/repos/pandas-d...   
2  {'url': 'https://api.github.com/repos/pandas-d...   
3  {'url': 'https://api.github.com/repos/pandas-d...   
4  {'url': 'https://api.github.com/repos/pandas-d...   

                                        timeline_url performed_via_github_app  
0  https://api.github.com/repos/pandas-dev/pandas...                     None  
1  https://api.github.com/repos/pandas-dev/pandas...                     None  
2  https://api.github.com/repos/pandas-dev/pandas...                     None  
3  https://api.github.com/repos/pandas-dev/pandas...                     None  
4  https://api.github.com/repos/pandas-dev/pandas...                     None  

[5 rows x 21 columns]

### Exercício 10

In [106]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3
import time
import os

os.remove("e10.db") if os.path.exists("e10.db") else None

conn = sqlite3.connect('e10.db')
cur = conn.cursor()

PermissionError: [WinError 32] O arquivo já está sendo usado por outro processo: 'e10.db'

In [90]:
prod1 = {'nome':'Geladeira','preco':2000.0, 'marca':'Samsung'}
prod2 = {'nome':'Televisão','preco':2500.0, 'marca':'LG'}
prod3 = {'nome':'Celular','preco':5600.0, 'marca':'Apple'}

prods = [prod1,prod2,prod3]

In [99]:
cur.execute('CREATE TABLE IF NOT EXISTS produtos('\
    'nome varchar(50),'\
    'preco decimal,'\
    'marca varchar(50) )')

In [93]:
class Produto():
    attr=['nome','preco','marca']
    def __init__(self,prod):
        self.nome = prod['nome']
        self.preco = prod['preco']
        self.marca = prod['marca']

In [102]:
def insert(prod):
    cur.execute('INSERT INTO produtos(nome,preco,marca) VALUES(?,?,?)',\
        [prod.nome, prod.preco ,prod.marca])

for prod in prods:
    p = Produto(prod)
    insert(p)
    time.sleep(2)
    

OperationalError: database is locked

In [96]:
t = cur.execute('select * from produtos')
t.fetchall()

[]

In [105]:
conn.close()

# Fim


### Obrigado

### Visite o Blog da Data Science Academy - <a href="http://blog.dsacademy.com.br">Blog DSA</a>
